### ISSUE TITLE
a screenshot wanted

### ISSUE THREAD

**Issue by asashnov** [amund7/CANBUS-Analyzer#1]
Could you please add some screenshots and README.md file
so everyone can have a feeling what this project does?

**Comment by amund7** [comment]
Good idea, will do!

**Comment by amund7** [comment]
But how can I actually add screenshots to readme.md? Or should I use wiki instead?

**Comment by amund7** [comment]
Finally done! Thanks for teaching me :)

**Comment by asashnov** [comment]
WOW, Perfect!
You are welcome :)
