### ISSUE TITLE
Choose which packet definitions to use (Model S, Model 3, Model S DBC, etc.)

### ISSUE THREAD

**Issue by Bokonon79** [amund7/CANBUS-Analyzer#18]
At the moment, CANBUS-Analyzer can only load the hard-coded Model S packet definitions for analysis. 

Adding a "mode" or "definitions" selector (e.g. dropdown list) to the UI would allow the user to switch between different analysis modes (assuming the modes are exclusive of one another). Options might include: 

Model S Defaults (hard-coded definitions)
Model 3 Defaults (hard-coded definitions)
Model S RWD DBC file
Model S AWD DBC file
Model 3 DBC file

**Comment by amund7** [comment]
I think we are close, if not already at where we could just load any DBC file for any car. So maybe the dropdown should be
- Model S (hard-coded)
- Model 3 (hard-coded)
- Load DBC file

the latter would pop up an open dialog. After loading several DBC files, they should stay in that box for quick select/load later on.

Just an idea, but we are moving fast towards compatibility with any DBC file, and we should start preparing the UI for it.

**Comment by brian-man** [comment]
Hope:
At some point hopefully there will be one or more packets we can use to identify the vehicle type enough to appropriately choose the right DBC file automatically.

**Comment by amund7** [comment]
I don't think we should stress that, if we support DBC files, we support ANY dbc file, right? Meaning, volvos, audis, school buses whatever.

But perhaps it can be done for model3 / S ?
